version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - auth_data:/var/lib/postgresql/data
volumes:
  auth_data:
